import { expect } from "chai"
import add from "../src/add.js"

describe("add.js", () => {
    describe("Part of initial test plan", () => {
        it("should return 2 with augend as 1 and addend as 1", () => {
            expect(add(1, 1)).to.equal(2)
        })

        it("should return 11 with augend as -1 and addend as 12", () => {
            expect(add(-1, 12)).to.equal(11)
        })
        
        it("should return -17 with augend as -10 and addend as -7", () => {
            expect(add(-10, -7)).to.equal(-17)
        })

        it("should throw an exception with augend as \"five\" and addend as \"ten\"", () => {
            expect(add("five", "ten")).to.throw()
        })
    })

    describe("Additional tests made by humans", () => {
        it("should return 11 with augend as -1 and addend as 12", () => {
            expect(add(-1, 12)).to.equal(11)
        })

        it("should return 4 with augend as 13 and addend as -9", () => {
            expect(add(13, -9)).to.equal(4)
        })

        it("should return -8 with augend as -15 and addend as 7", () => {
            expect(add(-15, 7)).to.equal(-8)
        })

        it("should return -20 with augend as 6 and addend as -26", () => (
            expect(add(6, -26)).to.equal(-20)
        ))

        it("should return 0 with augend as 5 and addend as -5", () => {
            expect(add(5, -5)).to.equal(0)
        })

        it("should return -9 with augend as -2 and addend as -7", () => {
            expect(add(-2, -7)).to.equal(-9)
        })

        it("should throw an exception with augend as \"two\" and addend as 5", () => {
            expect(() => add("two", 5)).to.throw()
        })
        
        it("should throw an expection with augend as 3 and addend as \"four\"", () => {
            expect(() => add(3, "four")).to.throw()
        })
    })

    describe('Tests generated by ChatGPT', () => {
        it('should add two positive numbers', () => {
            expect(add(6, 4)).to.equal(10);
        });

        it('should add negative numbers', () => {
            expect(add(-3, -7)).to.equal(-10);
        });

        it('should add a positive and a negative number', () => {
            expect(add(10, -3)).to.equal(7);
        });

        it('should add floating point numbers', () => {
            expect(add(0.1, 0.2)).to.be.closeTo(0.3, 0.0000001);
        });

        it('should return a number when given numeric strings (if coerced)', () => {
            expect(add('3', '4')).to.equal(7);
        });

        it('should return NaN when one argument is non-numeric', () => {
            expect(add(3, 'a')).to.be.NaN;
        });

        it('should return the other value if one argument is undefined (identity = 0)', () => {
            expect(add(undefined, 5)).to.equal(5);
            expect(add(5, undefined)).to.equal(5);
        });

        it('should return 0 if both arguments are undefined', () => {
            expect(add(undefined, undefined)).to.equal(0);
        });

        it('should handle null values (treated as 0)', () => {
            expect(add(null, 5)).to.equal(5);
            expect(add(5, null)).to.equal(5);
            expect(add(null, null)).to.equal(0);
        });
    });    
})
